### ISSUE TITLE
Setear todos los textos del lado del cliente

### ISSUE THREAD

**Issue by RecoX** [ao-libre/ao-cliente#1]
Setear todos los textos del lado del cliente

Link con un tutorial para hacerlo:

http://www.gs-zone.org/temas/cliente-y-servidor-13-3-dx8-v1.95611/

http://www.gs-zone.org/temas/reformas-en-hechizos-y-npcs-optimizacion.95735/

Link de interes
http://www.gs-zone.org/temas/continuidad-a-las-reformas-parte-objetos.95737/#post-812883

Link a tarea para multi-idioma:
https://github.com/ao-libre/ao-cliente/issues/27

**Comment by Derillo** [comment]
Estoy recopilando todos los textos que envía el servidor mas allá de los Hechizos y npc.
Para ello estoy haciendo búsquedas dentro del código.
Empece usando la palabra clave CONSOLE, luego Recox me sugirió usar = " y tuve que volver a compilar todos los módulos buscando strings que enviá el servidor (doble esfuerzo)
Para que no me vuelva a pasar lo mismo, podrían decirme que palabras claves de búsqueda tendría que buscar en el servidor que sean cadenas de texto que envía el servidor al cliente? (es la primera vez que leo de corrido el codigo de argentum xD)
También consulto, los logs que guarda el servidor, son necesarios cambiarlos?
Les dejo el formato que estoy usando:
Modulo | Linea de codigo |  ID | Texto Original | Actualización2018 | Descripción | Tipo de Mensaje
InvUsuario.bas | 1184 | 125 | Debes tener equipada la herramienta para trabajar. | Equipa la herramienta para poder utilizarla. | Caña de pesca o red | Información

**Comment by Derillo** [comment]
https://docs.google.com/spreadsheets/d/1qvifXgCCxirfCP8QiEUubDgNHsdIBkVn3gCWSuGzkXQ/edit?usp=sharing

Quién desee colaborar, por favor, solicite permisos de Edición. Gracias :)
