### ISSUE TITLE
Error 91

### ISSUE THREAD

**Issue by plusin** [ao-libre/ao-cliente#107]
Estaba en dorch, se largó a llover y empezó a tirar el error 91 provocándo el cierre del cliente, al reiniciar conexión tiró el mismo error, recién al 3er intento pude iniciar sesión normalmente.
Me acaba de pasar de nuevo después de unas horas, inicie sesión, elijo el PJ y me tira ese error.

Testeado en branch database16 y en release de la web.
![error91](https://user-images.githubusercontent.com/7727108/49328168-97ebd400-f54a-11e8-8992-fec858bb96f5.png)

**Comment by RecoX** [comment]
https://github.com/ao-libre/ao-server/issues/61

**Comment by RecoX** [comment]
No lo puedo reproducir, Win 7 64bits.

**Comment by plusin** [comment]
Continuar en: https://github.com/ao-libre/ao-server/issues/61
