### ISSUE TITLE
Recuperar Password / Borrar Personaje

### ISSUE THREAD

**Issue by RecoX** [ao-libre/ao-cliente#12]
Tenemos que arreglar esto ya que al momento no esta funcionando.

link de utilidad.
http://www.gs-zone.org/temas/recuperar-y-borrar-personaje-clave-pin-funcional.88705/

**Comment by RecoX** [comment]
Lo anterior queda obsoleto luego de la implementacion de base de datos.
Tenemos que crear un sistema para poder recuperar password de la cuenta deseada.

**Comment by jopiortiz** [comment]
Implementado.
