### ISSUE TITLE
Historial del CVS

### ISSUE THREAD

**Issue by aaferrari** [ao-libre/ao-cliente#136]
Revisando los commits veo que faltan los que se hicieron en el repositorio CVS. Pienso que podría ser útil fusionar los historiales de ambos repositorios, ya sea para rastrear cambios mas fácilmente o solo para tener la historia completa del código en caso de que el CVS deje de estar disponible. Lo mismo va para todos los repositorios de ao-libre traídos desde Sourceforge.
Hace tiempo hice lo mismo con [este programa](https://github.com/necrose99/abeni-reborn) y lo que tomo mas tiempo no fue la importación en si sino el ponerle los emails a los colaboradores y hacer un commit adicional para "empalmar" el ultimo cambio del CVS con los primeros commits del Git.
Si te interesa puedo hacer un repositorio de prueba con los historiales combinados, pero no es algo que se pueda combinar en un pull requests debido a que se esta reescribiendo el historial (en [este issue](https://github.com/necrose99/abeni-reborn/issues/4) se puede entender mejor como se resolvió el tema con el programa ya mencionado).

**Comment by RecoX** [comment]
Estaria muy bueno poder fusionar eso asi poder hacer un rastreo mas ordenado de como fue evolucionando todo.

Si hay alguna forma de hacerlo sin dedicarle mucho tiempo al mismo y que no traiga complicaciones, estoy 100% interesado =D

**Comment by RecoX** [comment]
@aaferrari Despues de un lindo trabajo termine de hacerlo para todos los repositorios que estaban en Sourceforge, he enviado email y contactado con todos los que pude faltan las siguientes personas que no respondieron:
```
amraphen = amraphen <amraphen@users.sourceforge.net>
arminasggv = arminasggv <arminasggv@users.sourceforge.net>
brianpr = brianpr <brianpr@users.sourceforge.net>
byval = byval <byval@users.sourceforge.net>
grimmjaw = grimmjaw <grimmjaw@users.sourceforge.net>
integer_nacho = integer_nacho <integer_nacho@users.sourceforge.net>
jamicheli = jamicheli <jamicheli@users.sourceforge.net>
ltourrilhes = ltourrilhes <ltourrilhes@users.sourceforge.net>
markoxx = markoxx <markoxx@users.sourceforge.net>
niconz = niconz <niconz@users.sourceforge.net>
nmg86 = nmg86 <nmg86@users.sourceforge.net>
noich = noich <noich@users.sourceforge.net>
rapsodius = rapsodius <rapsodius@users.sourceforge.net>
salvito = salvito <salvito@users.sourceforge.net>
salvito_u = salvito_u <salvito_u@users.sourceforge.net>
tavo_92 = tavo_92 <tavo_92@users.sourceforge.net>
toxicwaste = toxicwaste <toxicwaste@users.sourceforge.net>
```

Cree un tutorial para que se sepa como importar un proyecto de sourceforge a github
https://medium.com/@requitolucas/importar-repositorio-cvs-a-git-sourceforge-a-github-de-manera-facil-20c63344bfa5

Ya que la fuente citada 
http://olegp.name/howto/convert-sourceforge-cvs-to-git/
usa la herramienta git cvsimport la cual es obsoleta al dia de hoy.
