### ISSUE TITLE
Caida del servidor por bucle infinito

### ISSUE THREAD

**Issue by Juanmz** [ao-libre/ao-cliente#144]
Al tener un mapa mal mapeado puede pasar que se produzca un bucle infinito de tile-exit. Provocando un overflow de stack.

**Comment by RecoX** [comment]
Cuales son los pasos a seguir para poder reproducir este bug ?

Cual seria una solucion a este problema ?

**Comment by Juanmz** [comment]
Los pasos son simples pones un traslado que te lleve a la pos de otro traslado y ese traslado te mande al otro. La solución seria que si a la pos que voy a ser tele-transportado hay un tile-exit no lo dejo pasar.
