### ISSUE TITLE
[Error] Modo Seguro (Mensaje) Botón *

### ISSUE THREAD

**Issue by Bassinger** [ao-libre/ao-cliente#149]
> El tema es el botón * (Modo seguro para atacar a ciudadanos) 

Antes que nada, lo que es el funcionamiento del sistema esta perfectamente, solamente ahí un pequeño detalle que se ha sobresaltado, que es el mensaje en el cada vez pulsas dicho botón. ¿Parece pamplina, verdad? Pero como se quedaría el usuario al ver que pulsa el botón y se queda sin saber si ha activado o desactivado, o funciona? .. pues no es tan pamplina.

Public Const MENSAJE_SEGURO_ACTIVADO As String = ">>SEGURO ACTIVADO<<"
Public Const MENSAJE_SEGURO_DESACTIVADO As String = ">>SEGURO DESACTIVADO<<"

Su mensajes están declaradas, básicamente se tendría que añadir dicha llamada en su handle. :P

**Comment by jopiortiz** [comment]
Ya no se usa una constante para definir el texto de un mensaje. Se arregló al implementar el nuevo sistema multi-lenguaje.
