### ISSUE TITLE
Clon al conectar

### ISSUE THREAD

**Issue by Bassinger** [ao-libre/ao-cliente#158]
Me pasó conectando con varios personajes de la misma cuenta. El personaje clonado falso está en la posición donde conecté con otro personaje.
![clon](https://user-images.githubusercontent.com/31661806/52754399-a8b0cf80-2ffa-11e9-8845-a4e4d2ba9d23.jpg)

**Comment by Bassinger** [comment]
Mensaje de un usuario en #programacion 


Sparksedhoy a las 19:38
Ya que estamos aca, tengo una duda, no se si alguien estuvo jugando al ofi en 2015 a la 13.0, pero hubo una epoca en donde fui literalmente participe indirecto de que el server se vaya a la mierda y no se si tuvieron que ver ddos o etc.
Estabamos de madrugada y no se que mierda me pasa a mi, pero en ullathorpe mi pj se multiplica en el comerciante que compra y vende todo, se forman como 8 clones al rededor de este, que conforme yo me movia, estos clones hacian la animacion de moverse para el lado a donde yo iba pero permanecian en el lugar en donde estaban.
Con una amiga mia, y otras personas nos empezamos a cagar de la risa pero se puso peor cada vez, desloguie mi cuenta y seguia todo eso, y se habia puesto peor, en todos los mapas en el x 50 e y 50 aparecia un clon mio ahi en medio de todo, no me acuerdo si se le podia clickear o no pero me acuerdo que no podias pasar sobre el y en todos los mapas ocurría, despues de eso me acuerdo que la 13.0 cerro, no tengo capturas de eso ahora porque formatie a la mierda la pc y mentir de esto no me serviria de nada, desde entonces sigo buscando a alguien que haya estado esa noche o que sepa decirme que mierda paso, que encima despues de todo eso el 13.0 se fue a la mierda

**Comment by Yhunja** [comment]
Solución: meter esto en algún lado
```
Sub CleanerPlus()
   Dim x As Long
   Dim y As Long

  For x = UserPos.x - 8 To UserPos.x + 8
   For y = UserPos.y - 6 To UserPos.y + 6

       If (MapData(x, y).CharIndex) Then
         Call Char_Erase(.CharIndex)
       End If

      If (MapData(x, y).ObjGrh.GrhIndex) Then
        Call Map_DestroyObject(x, y)
      End If

   Next y
 Next x
 
End Sub
```
En el sub switchmap arriba de la carga del archivo .map llamas a la función.

**Comment by Bassinger** [comment]
Buenas.
Cambiar esto
Call Char_Erase(.CharIndex)
por esto.
Call Char_Erase(CharIndex)
Gracias por el aporte Yhunja.

**Comment by Bassinger** [comment]
Pd: Sigue el bug

**Comment by Yhunja** [comment]
Ya había editado el texto fijate copiando y pegando el código nuevamente.
cambié esto

`Call Char_Erase(.CharIndex)`

por:

`Call Char_Erase(MapData(x, y).CharIndex)`

y esto:

```
For x = UserPos.x - 8 To UserPos.x + 8
   For y = UserPos.y - 6 To UserPos.y + 6
```

por:

```
For x = XMinMapSize To XMaxMapSize
       For y = YMinMapSize To YMaxMapSize
```

**Comment by Bassinger** [comment]
Ahora si, grande maquina!
