### ISSUE TITLE
Números informativos sobre el personaje

### ISSUE THREAD

**Issue by Derillo** [ao-libre/ao-cliente#160]
### **InfoRenderTarget(sobre ellos)**
**Duración**
2seg

**Efecto**
Desbanecimiento Descendente. de Alpha 100 a 55% , de font 12 a 0 y con elevación de 
- GolpeAlCuerpo o Magia (probar si con el grafico de los hechizos no queda muy chico o grande)
InicioXY=290,240,Color
FInalXY=290,290,Color
- GolpeCabeza
InicioXY: 290,260
FInalXY=290,290

**Colores**
**Daño:** ColorRojo
**Apuñalado:** ColorAmarillo
**Curar:** ColorVerde
**Has fallado:** Color gris texto = "Fallas"

### **InfoRenderMy(sobre nosotros):**
**Duración**
2seg
**Efecto**
Aparecimiento Ascendente. de Alpha 35 a 100% , de font 3 a 8 y con elevación de 
- GolpeAlCuerpo o Magia o Experiencia (probar si con el grafico de los hechisos no queda muy chico o grande)
Al revés de target
-  Golpe Cabeza
**Colores
- Daño Recibido: ColorRosa
- Apuñalado: ColorNaranja
- Cura: ColorVerde
- Experiencia Recibida: ColorGris
- Has fallado: Color gris texto = "Evades"

## Posibles Formas de implementación por Comunidad Gs-Zone
https://www.gs-zone.org/temas/danos-en-render-bien-hechos-base.95207/
https://www.gs-zone.org/temas/dano-en-render-npc-y-usuarios.95098/

**Comment by RecoX** [comment]
Esto ya fue implementado :)
