### ISSUE TITLE
Error Explota billetera con 500.000k o mas

### ISSUE THREAD

**Issue by Derillo** [ao-libre/ao-cliente#174]
Cuando tenes mas de 500 000 de oro, explota lo que tengas de mas
Sucede cuando te ejecutan y cuando te matan

**Comment by FrankoH298** [comment]
Eso es asi, por cada nivel, vos podes guardar en tu billetera 10000 de oro.
Si sos nivel 40, vas a proteger hasta 400k y el excedente se caerá.
