### ISSUE TITLE
KeyBoard Config predefined - Saved in Account

### ISSUE THREAD

**Issue by Derillo** [ao-libre/ao-cliente#186]
### Config Default
Arriba> Arriba
Abajo> Abajo
Izquierda > Izquierda
Derecha > Derecha
Agarrar > A
Equipar > E
Domar > D
Robar > R
Ocultar > O
Tirar > T
Usar > U
**Atacar > Shift (se quita del default el Control ya que en windows genera un cartel cuando lo apretas varias veces seguida)**
Hablar a todos > Enter
Hablar a clan > Suprimir
**ELIMINAR> Activar/desacticar Musica > M**
Corregir Posición > L (El cliente lo tendría que hacer automaticamente, no debería existir)
Mostrar OcultarNombres> N
Activar Desactivar Sonido > S
**ELIMINAR> Activar Desactivar Fx> F**
Capturar Pantalla> F2
**Mostrar Opciones > Esc** (la cambio porque no se justifica mantener el F5 ocupado para esto, en todos los juegos se usa Esc) #159 
Meditar > F6
Macro Hechizos >F7
Macro Trabajo > F8
**ELIMINAR> Salir > F12 (existe un boton para salir)**
Modo Seguro > *
Seguro de resucitaci{on > Fin
**Mostrar Mapa > TAB**

### Config Predefined 1:
Arriba>W
Abajo> S
Izquierda > A
Derecha > D
Agarrar > R
Equipar > E
Domar > G
Robar > X
Ocultar > C
Tirar > T
Usar > F
Atacar > Shift 
Hablar a todos > Enter
Hablar a clan > Suprimir
Corregir Posición > L (El cliente lo tendría que hacer automaticamente, no debería existir)
Mostrar OcultarNombres> N
Activar Desactivar Sonido > S 
Mostrar Opciones > Esc
Meditar > F1
Capturar Pantalla> F2
Macro Hechizos >F3
Macro Trabajo > F4
Modo Seguro > B
Seguro de resucitaci{on > V
**Mostrar Mapa > TAB**
- ### Agregados
Macro Combate 1> 1
Macro Combate 2> 2
Macro Combate 3> 3
Macro Combate 4> 4

**Comment by Derillo** [comment]
Podríamos hacer un boton en la interfaz para acceder a la configuración directamente y/o agregar una imagen del teclado en el tutorial de inicio con el preset default resaltado.

**Comment by RecoX** [comment]
Esto ya fue implementado :)
