### ISSUE TITLE
Utilizacion de multiples mundos y mapas

### ISSUE THREAD

**Issue by RecoX** [ao-libre/ao-cliente#188]
Se necesita hacer que el cliente sea capaz de utilizar multiples mundos

Se necesita crear una carpeta llamada Mundos y dentro de la misma que esten todos los mundos disponibles para Argentum.

1- Al hacer click en un server en la lista de servers, el server enviara al cliente un string diciendo el nombre del mundo a utilizar en caso que el cliente no tenga el mundo instalado en la nueva carpeta mundos, debera aparecer un msgBox avisando de esto (en el futuro se hara que se autodescarguen los mapas como en el juego counter-strike, esto no es parte de esta primer parte del proceso)

2- Al conectar setear una variable global con el nombre del mapa e utilizarla en como apendice en DirMapas donde se utiliza los mapas quedando algo asi:

```
Public Function DirMapas() As String
    DirMapas = App.path & "\" & Config_Inicio.DirMapas & WolrdNameUsedByServer & "\"
End Function
```

**Comment by Derillo** [comment]
Estructura Raiz
Mapas>
m1
m2
m3
.mx (viene en el string a cual tiene que acceder)

**Comment by Derillo** [comment]
\
Mapas>
 peligrosas-catacumbas-m001
 el-retorno-de-mordor-m002
 x-mxxx

Se accede a la carpeta solo con los ultimos 4.Esta opcion le da más lectura a la estructura de carpetas.

**Comment by Juanmz** [comment]
En el paquete del ChangeMap se envía un dato mas un BYTE que seria el numero de mundo y la versión del mapa. Si la versión es distinta a la del cliente manda a descargar el nuevo mapa y si no existe el mapa también.

**Comment by RecoX** [comment]
Esto seria despues de logear, cuando estoy por entrar con mi personaje al juego o al seleccionar un server de la lista ?

**Comment by Juanmz** [comment]
Al recibir la información del mundo, mapa y version del mismo, osea al logear un pj

**Comment by Juanmz** [comment]
Sino la otra que se me ocurre es que al abrir el AO busque actualizaciones de cualquiera de los mundos y las descargue

**Comment by RecoX** [comment]
Hagamosla practica para poder hacerla, luego podemos siempre mejorarla.

1- Al conectarme a un servidor, cuando me logeo con un personaje verificar que tenga el mundo instalado en la carpeta `Mundos/NOMBRE_DEL_MUNDO` caso positivo me logeo, caso negativo mostramos un mensaje de error diciendo que no se tiene el mapa instalado que hay que descargarlo y salimos del servidor.

Basicamente eso tendria que hacer el cliente.

**Comment by Juanmz** [comment]
El tema de los mundos se me ocurre que podria validarlo el cliente sin preguntarle nada al servidor que cuando clickee la lista analice las versiones de los mapas que estan subidos al hosting web

**Comment by Juanmz** [comment]
Lo único que enviaría el servidor seria el numero del mundo. Y el cliente se encarga de verificar todos los mapas.

**Comment by Juanmz** [comment]
A logear y al deslogear

**Comment by RecoX** [comment]
Ok hagamos eso

Cliente:
1- Nosotros controlariamos el versionado y variedad de los mundos mediante un servidor (github)
2- Al conectarme a un servidor, cuando me logeo con un personaje verificar que tenga el mundo instalado en la carpeta Mundos/NOMBRE_DEL_MUNDO caso positivo me logeo, caso negativo mostramos un mensaje de error diciendo que no se tiene el mapa instalado que hay que descargarlo y salimos del servidor. En teoria esto no tendria que pasar ya que lanzariamos los mundos nuevos con los releases.

Server:
1- Nosotros controlariamos el versionado y variedad de los mundos mediante un servidor (github)
2- Al logearse un usuario debemos enviar informacion del mundo que el server utiliza para poder configurar el cliente de forma correcta.
3- Se podra elegir que mundo usar desde una opcion en el `server.ini`
