### ISSUE TITLE
Run-Time Error '-2005401530 (88780046)': Automation Error

### ISSUE THREAD

**Issue by HakuGM** [ao-libre/ao-cliente#195]
Un chico creo un personaje y no lo dejaba ver su inventario (pero si se podía equipar la ropa) ni moverse por el mapa solo lo dejaba agarrar items, lo ejecuto como administrador y lo mismo, juega desde una notebook, lo pueden arreglar por favor!, gracias!

**Comment by RecoX** [comment]
Agrego foto que le pasa:

https://media.discordapp.net/attachments/560170902910795787/560467082052108377/Sin_titulo.png?width=832&height=468
