### ISSUE TITLE
Implementar Mini Mapa (Agregar todos los .BMP de los 290 mapas que hay, arreglar punto con posicion)

### ISSUE THREAD

**Issue by RecoX** [ao-libre/ao-cliente#2]
Implementar minimapa mostrando el tile exacto donde el personaje esta parado.

**Comment by RecoX** [comment]
La implementacion fue hecha aqui se ve como
https://github.com/ao-libre/ao-cliente/pull/169/files

El mini-mapa lee las imágenes (.bmp) de la carpeta "MiniMapa" en Graficos. Es semi-transparente y desaparece al pasarle el mouse.


Trabajos que queda por hacer:
TO-DO: Agregar todos los .BMP de los 290 mapas que hay. Traté de hacerlo pero el WE no me los guarda. :'(
TO-DO: Arreglar el punto rojo que no se mueve.

Extraído de KuviK AO.

**Comment by jopiortiz** [comment]
Implementado.
