### ISSUE TITLE
Implementar restriccion de hechizos por clase

### ISSUE THREAD

**Issue by RecoX** [ao-libre/ao-cliente#20]
Simple, es como con los objetos nada más que con los hechizos. Al querer aprender un hechizo que tenemos el objeto en el inventario y queremos que por ejemplo nomas lo puedan tener los magos, sale en consola "Tu clase no puede aprender este hechizo". Se datea el objeto del hechizo con las clases prohibidas (CP's) correspondientes como cualquier otro objeto

http://www.gs-zone.org/temas/hechizos-por-clase.93770/

**Comment by jopiortiz** [comment]
Esto se hace en el Servidor...
