### ISSUE TITLE
Stat de vida para los bichos

### ISSUE THREAD

**Issue by neoranger** [ao-libre/ao-cliente#222]
Estaría bueno que se pueda ver la vida de los bichos que uno se cruza por el camino.
Pueden ser 2 opciones:
- Empezar a ver su vida una vez que uno comienza a atarcarlos
- Por medio del acercamiento. Estando a tal número de tiles que muestre o no la vida a ese PJ que pasa por ese bicho.

**Comment by jopiortiz** [comment]
Podes ver la vida de los bichos al tener un nivel alto de la Skill supervivencia.
