### ISSUE TITLE
Optimizar texturas.

### ISSUE THREAD

**Issue by jopiortiz** [ao-libre/ao-cliente#238]
https://www.gs-zone.org/temas/base-texture-atlas.85473/

**Comment by Wolftein** [comment]
Eso no sirve si no va acompañado de una clase que haga batching y ordene las llamadas. Te recomiendo primero implementar una clase que haga un simple batching.

Aca tenes algo para empezar https://github.com/Rhynne/Fenix13/blob/master/client/CODIGO/clsBatch.cls

**Comment by FrankoH298** [comment]
Hecho por @jopiortiz
