### ISSUE TITLE
Nombres 

### ISSUE THREAD

**Issue by Fitonga** [ao-libre/ao-cliente#240]
Bueno sin mas que decir , miren...

![Sin título](https://user-images.githubusercontent.com/32013436/58900910-72e14500-86d6-11e9-8d25-899dade1b9c2.jpg)

Mis specs: Windows 7 32 bits , 

![d2d2d2d](https://user-images.githubusercontent.com/32013436/58900994-9906e500-86d6-11e9-86e0-2ff8447134a5.jpg)

**Comment by neoranger** [comment]
Es un tema que se había corregido pero quedó feo. El equipo de programación ya lo sabe y lo tiene en cuenta para próximas releases.
Saludos!

**Comment by jopiortiz** [comment]
Arreglado #248
