### ISSUE TITLE
Implementar/Mejorar sistema de particulas en el juego

### ISSUE THREAD

**Issue by RecoX** [ao-libre/ao-cliente#250]
En este caso seria algo asi como:

Implementar/Mejorar sistema de particulas en el juego
- Implementar particulas al lanzar un hechizo a un pj o npc
- Implementar particulas al pegarle a un npc con un arma/mano
- Implementar particulas al hacer acciones como Teletransportarse
- Implementar particulas al ser curado por un cura
- Implementar particulas al tomar una pocion, tomar agua o comer alimento
- Implementar particulas al aprender hechizo

Las particulas de los hechizos se definiran en el archivo `Hechizos.dat` con el resto de las propiedades del mismo.

**Comment by cucsijuan** [comment]
el unico tema es que las particulas son dependientes del codigo, me refiero a las animaciones, tendrias que definir varios tipos de animaciones y quizas si lo que podria ser un parametro es el sprite, el tamaño del sprite, color y no se si se podra algo mas. Pero es buena idea implementar este sistema.

**Comment by RecoX** [comment]
te referis a algo asi?
```
[191]
Name=Meditaci�n 55-59 (Renegado)
NumOfParticles=125
X1=25
Y1=-1
X2=-25
Y2=1
Angle=0
VecX1=0
VecX2=0
VecY1=60
VecY2=60
Life1=5
Life2=70
Friction=3
Spin=0
Spin_SpeedL=1
Spin_SpeedH=1
Grav_Strength=2
Bounce_Strength=-5
AlphaBlend=1
Gravity=0
XMove=1
YMove=1
move_x1=-5
move_x2=5
move_y1=-30
move_y2=10
life_counter=-1
Speed= .1
resize=0
rx=0
ry=0
NumGrhs=3
Grh_List=20000,19997,19990,
ColorSet1=255,30,93
ColorSet2=255,255,255
ColorSet3=244,41,132
ColorSet4=255,132,255
FadeOut=45
```

En este archivo de recursos extraidos de IAO hay unas 237

[particulas.txt](https://github.com/ao-libre/ao-cliente/files/3459372/particulas.txt)

**Comment by cucsijuan** [comment]
eso! por lo que veo pueden ser bastante configurables, se pueden exponer un monton de parametros

**Comment by jopiortiz** [comment]
Esos parámetros de configuración se ven en los códigos que tienen el Sistema de Partículas ORE.
