### ISSUE TITLE
Los objetos NO usables si se usan te kickea del juego, arreglarlo

### ISSUE THREAD

**Issue by RecoX** [ao-libre/ao-cliente#251]
los objetos NO usables si se usan te kickea del juego, arreglarlo

hacer que no se puedan usar cosas como el Mueble rustico

**Comment by Wyr0X** [comment]
No lo puedo replicar. Está fixeado ya?

**Comment by jopiortiz** [comment]
[Arreglado.](https://github.com/ao-libre/ao-server/pull/184)
