### ISSUE TITLE
Implementacion Multi-idioma en el juego

### ISSUE THREAD

**Issue by RecoX** [ao-libre/ao-cliente#27]
Se creara la posibilidad de tener el juego en multiples lenguajes.

Para esto es necesario:
Permitir cambiar el idioma en opciones.
Setear en el archivo de configuracion el lenguaje escogido por el usuario
Crear archivos de texto (JSON)
Obtener strings desde el archivo en el lenguaje especificado.

Link de utilidad para parsear JSON en vb6
http://www.ediy.co.nz/vbjson-json-parser-library-in-vb6-xidc55680.html

Para el apartado grafico de botones, hay que eliminar todas las imagenes y reemplazarlas por labels, pero no es parte de esta tarea.

**Comment by aaferrari** [comment]
En [este tutorial](https://www.vb-helper.com/tut9.htm) también hay otras formas de internacionalizar un programa en Visual Basic.

**Comment by RecoX** [comment]
Gracias @aaferrari, la idea que se propone aca es muy similar al del sitio que pasaste, es basicamente sacar los strings a un archivo de recursos, pero es mejor hacerlo en JSON y no en un formato obsoleto ya que esto puede ser reutilizado mas facilmente.

**Comment by jopiortiz** [comment]
Implementado en el pull #153
