### ISSUE TITLE
Eliminación de PJ

### ISSUE THREAD

**Issue by samuh1125** [ao-libre/ao-cliente#280]
Sería interesante que dentro de las opciones del "panel F5" se pueda borrar el char. 
el ao es un juego muy competitivo y la vida del pj siempre fue importante, tener el limite de crear 10 pjs imposibilita "tirar vidas"

Había servidores que incluían un comando /reset donde permitía comenzar de nuevo un pj.
Habría que delimitar bien los paramestros válidos, se me ocurre que el comando sea valido para:
- pj nw o menor a 13.
- reset completo (nivel, vida de nacimiento, posición de raspawn, oro)

**Comment by RecoX** [comment]
Hecho, ahora se pueden borrar pjs
