### ISSUE TITLE
Agregar ... arriba de los pjs cuando los mismos estan tipeando

### ISSUE THREAD

**Issue by RecoX** [ao-libre/ao-cliente#299]
Muchas veces uno chatea en el AO y no sabe si la otra persona esta IDLE o esta ahi escribiendo.

Estaria muy bueno agregar un simbolo con ... para indicar que la otra persona esta tipeando algo

**Comment by RecoX** [comment]
![asdasd](https://user-images.githubusercontent.com/5874806/64916837-883c3400-d7da-11e9-9bdd-53c25c5dd42f.PNG)
Imagen de ejemplo

**Comment by Asdolo** [comment]
Interesante. Hay que tener cuidado de **NO** enviar el paquete "Estoy tipeando" al server cada vez que cambia el contenido del TextBox del chat para no saturar el server (y porque no tiene sentido). 

Hay dos formas de implementar esto.

1. Mostrar el globito cuando apreto enter y la caja de texto se pone en modo escribir. Luego ocultar el globito cuando envio el mensaje.

2. Mostrar el globito recien cuando empiezo a escribir algo y durante unos segundos, y que desaparezca solo si pasaron unos segundos sin haber escrito nada (todavia sin haber enviado el mensaje).

**Comment by RecoX** [comment]
Agregando al comentario de @Asdolo, hacer una validacion para que no envie ese paquete al server en caso de que el primer caracter sea `/` ya que el ususario estaria escribiendo un comando.

**Comment by CuicuiEB** [comment]
Algo así? https://youtu.be/jtmdALe5ASE
