### ISSUE TITLE
/buscar hacer que convierta tildes

### ISSUE THREAD

**Issue by RecoX** [ao-libre/ao-cliente#338]
cuando quiero buscar items que en el nombre tienen tilde no los encuentra, caso de las tunicas.

Hacer que se pueda buscar sin tildes.

**Comment by jopiortiz** [comment]
Para hacer eso hay que sacar todos los tildes del obj.dat

**Comment by RecoX** [comment]
No creo que sea asi realmente, ya que existe una funcion que hace la conversion en el server


```
Public Function Tilde(ByRef data As String) As String

    Dim temp As String

    'Pato
    temp = UCase$(data)
 
    If InStr(1, temp, "Á") Then temp = Replace$(temp, "Á", "A")
   
    If InStr(1, temp, "e") Then temp = Replace$(temp, "e", "E")
   
    If InStr(1, temp, "Í") Then temp = Replace$(temp, "Í", "I")
   
    If InStr(1, temp, "Ó") Then temp = Replace$(temp, "Ó", "O")
   
    If InStr(1, temp, "U") Then temp = Replace$(temp, "U", "U")
   
    Tilde = temp
        
End Function
```

Aunque estoy a favor de sacarle las tildes a los nombres de los objetos, ya que sinceramente generan mas dolores de cabeza que otra cosa.

**Comment by Asdolo** [comment]
No creo que haya que sacar las tildes de los nombres sólo para esto, es un problema específico del contexto del comando `/buscar`.

Acá hay una función un poco mejor para remover tildes y otros caracteres especiales. Es un poco más escalable, ya que no está llena de `If`s...

https://social.msdn.microsoft.com/Forums/vstudio/en-US/8392f4d3-e016-4337-9d37-fb20fecd1425/converting-string-with-accented-characters-to-nonaccented-equivalent?forum=vbgeneral

**Comment by RecoX** [comment]
> 
> 
> No creo que haya que sacar las tildes de los nombres sólo para esto, es un problema específico del contexto del comando `/buscar`.
> 
> Acá hay una función un poco mejor para remover tildes y otros caracteres especiales. Es un poco más escalable, ya que no está llena de `If`s...
> 
> https://social.msdn.microsoft.com/Forums/vstudio/en-US/8392f4d3-e016-4337-9d37-fb20fecd1425/converting-string-with-accented-characters-to-nonaccented-equivalent?forum=vbgeneral

El problema real es VB6 como maneja su encoding el cual no se lleva muy bien con como lo usa GIT
https://www.di-mgt.com.au/howto-convert-vba-unicode-to-utf8.html


Git al hacer un commit/merge etc internamente encodea las cosas a UTF8 (cosa que no se puede modificar con .gitattributes) la unica forma de poder evitar esto es que cuando se instala GIT en las computadoras es setear la opcion KEEP FILE AS IS o algo asi


por eso mismo y para evitar caracteres rotos y hacer mas facil la vida de todos, incluyendo poder usar el editor web de github, ya le sacamos todos y cada uno de los acentos al juego, solo nos faltaria reemplazar las `Ñ`  lo cual es complicado.

**Comment by Asdolo** [comment]
Digamos, la solucion ideal sería que tanto el Server como el Cliente carguen los strings de traducciones de un archivo/base datos/JSON con su codificación correcta, y no harcodearlos adentro del codigo de VB6, cosa que hace que explote el IDE.

**Comment by RecoX** [comment]
> 
> 
> Digamos, la solucion ideal sería que tanto el Server como el Cliente carguen los strings de traducciones de un archivo/base datos/JSON con su codificación correcta, y no harcodearlos adentro del codigo de VB6, cosa que hace que explote el IDE.

Todos los acentos y Ñ ya fueron reemplazados dentro del codigo (esto fue hace 2 aÑos ya que explotaba el codigo como decis vos).

Los archivos de recursos (el .dat en este caso que esta en formato INI) tenia los acentos pero cuando VB6 lee ese archivo ahi empieza el problema el cual explica el link que te pase arriba y por eso aparecen caracteres rotos dentro del juego. (Aguila se veia algo asi Ag┼la)

Esto ya no representa un problema real ya que los objetos y npcs no contienen mas tildes ni caracteres especiales, la unica excepcion a esta regla que queda por limpiar es la Ñ

**Comment by RecoX** [comment]
Cierro ya que que el juego no contiene mas Ñ y tildes y no deberiamos agregar las mismas para evitar romper.
