### ISSUE TITLE
clsBatch = FPS (LOTS OF FPS)

### ISSUE THREAD

**Issue by imASas** [ao-libre/ao-cliente#38]
Este modulo de clase mejora el engine y aumenta mucho los fps.

Cliente donde está implementado:
https://www.4shared.com/rar/H9ItvswPei/Proyecto_X.html

**Comment by juandpr** [comment]
Alguna punta sobre como encarar esto?

**Comment by Wolftein** [comment]
Aca se encuentra implementado https://github.com/Rhynne/Fenix13/tree/master/client/CODIGO , solo requiere un par de cambios en el modulo de TileEngine.
