### ISSUE TITLE
Agregar lista servidores preferidos

### ISSUE THREAD

**Issue by RecoX** [ao-libre/ao-cliente#4]
En el menu conectar tenemos que crear una lista donde se guarden todos los servidores que vamos entrando/agregando, permitiendo al usuario hacer click sobre un servidor en la lista y cambiar los parametros de conexion para poder conectarse al servidor elegido.

Se deberan guardar los siguientes parametros:

    Nombre servidor.
    Puerto.
    Ip

Guardar/Leer lista en el archivo INIT/sinfo.dat

Verificar el uso del parametro P2 y si esta en deshuso eliminar. (creo que tiene algo que ver con estadisticas del servidor)

Leer SINFO.dat desde github

https://raw.githubusercontent.com/ao-libre/ao-cliente/master/INIT/sinfo.dat

y la gente podria agregar su servidor a la lista mandando un PULL REQUEST

**Comment by cucsijuan** [comment]
P2 era para el password recovery que algún momento se habrá usado, no sirve.
