### ISSUE TITLE
Errores en comandos

### ISSUE THREAD

**Issue by RecoX** [ao-libre/ao-cliente#42]
Bassinger reporto al crear el indice de comandos:
[BUGS ENCONTRADOS]

/MIEMBROSCLAN : Solucionado: Falta en carpeta guilds con su .inf en el Servidor.

/BORRARPENA : Este comando se utiliza borrarpena nick+minutos de cárcel que ya tiene+sumar o restar los minutos de carcel. Eso suena más, un change/cambio que un borrador, creo que se debería de dividir el comando, o hacer que directamente al poner Nick borre la pena. Porque si lo pone solo con Nick no funciona el comando.

/AI1 /AI2 /AI3 /AI 4 Tanto /AC1 /AC2 /AC3 /AC4 no funcionan, pero si ponemos, /AI ó /AC funcionan. Desde luego… si veo los códigos vienen numeral..

/Mod Bassi Skills Combate sin Armas 90 No funciona Combate sin Armas, lo checkeo el usuario Mdatas.

**Comment by plusin** [comment]
Agrego el comando /LIMPIAR que está dentro de /PANELGM creo que sería interesante poder limpiar los elementos del piso con este comando siempre y cuando esté pensando para esta funcion, caso contrario tratar de insertarla en el ao-server. ¡gracias!
