### ISSUE TITLE
Invalid character in "Welcome" message

### ISSUE THREAD

**Issue by juandpr** [ao-libre/ao-cliente#48]
CODIGO/General.bas
Line 953

Call AddtoRichTextBox(frmCargando.Status, "                    Â¡Bienvenido a Argentum Online!"

**Comment by RecoX** [comment]
This is still happening.

**Comment by juandpr** [comment]
```
Call AddtoRichTextBox(frmCargando.status, "                    ¡Bienvenido a Argentum Online!", 255, 255, 255, True, False, True)
```

in `master` and `16_Database_Integration`

**Comment by juandpr** [comment]
I found the error in another part of the code, fixed it in `16_Database_integration`
