### ISSUE TITLE
Bug FXs `*No se muestran los fxs de los hechizos al matar un npc*`

### ISSUE THREAD

**Issue by Bassinger** [ao-libre/ao-cliente#51]
He creado un vídeo explicativo al problema para que podáis darle un vistazo.

>  https://www.youtube.com/watch?v=bIlxqnFXsf4

El problema es simple como el título lo dice:

 - A los usuarios, cuando mueren, salen el comienzo del FXs, y en cuanto a los NPC no muestran los FXs.

PD: Lo mismo esta bien y es así, porque también lo visto ahora mismo pasar en otro server, pero nose, mi manera de pensar es: que debe salir el fxs completo si lo tiras..

**Comment by cucsijuan** [comment]
Ver si tiene relación con esto
http://www.gs-zone.org/temas/arreglar-bug-cuando-te-pega-un-npc-se-le-termina-el-fx.94983/
