### ISSUE TITLE
Mercader

### ISSUE THREAD

**Issue by ReyarB** [ao-libre/ao-cliente#512]
Ver El mercader compra objetos y no los pone a la venta se saltea una linea de item y descuenta de una ventana pero de su propia ventana NO.

**Comment by ReyarB** [comment]
NPC 80  veo que tiene 35 objetos pero no los muestra a todos.

**Comment by RecoX** [comment]
Donde ves eso?

https://github.com/ao-libre/ao-server/blob/master/Dat/NPCs.dat
aca solo veo esto:

```
[NPC80] 'Mercader
Name=Mercader
NpcType=0
Desc=Hola buen amigo, compro y vendo todo tipo de mercancias!!
Head=2
Heading=3
Body=3
Movement=1
Attackable=0
ReSpawn=0
Hostile=0
Domable=0
Alineacion=0
Comercia=1
TipoItems=1000
NROITEMS=6
Obj1=1127-1000 'Manual de Liderazgo
Obj2=1128-1000 'Manual de Supervivencia
Obj3=1129-1000 'Manual de Navegacion
Obj4=866-1000 'Mochila del viajero
Obj5=865-1000 'Alforja
Obj6=1126-1000 'Amuleto de Silencio
BackUp=1
```

**Comment by ReyarB** [comment]
No esta bien, tambien prueben venderle objetos que no tenga, verán que no descuenta de la ventana frmComerciar pero si frmMain
