### ISSUE TITLE
Que dejen de rebotar los botones por favor!!!

### ISSUE THREAD

**Issue by neoranger** [ao-libre/ao-cliente#515]
Es super antiestético ver como esos botones rebotan en el cliente. La verdad es un efecto que es bastsnte de gusto cuando tranquilamente podrían estar los botones comunes y funciona igual. No se que le parece a los demás, pero a mi no me gusta.

Saludos.

**Comment by abusiv0** [comment]
estoy de acuerdo

**Comment by neoranger** [comment]
Gente, refuerza éste issue. Sé que es super superficial pero la verdad rompe mucho las bolas y atrasa un montón que sigan rebotando los botones una vez que se cierra el juego y vuelve al cliente.

**Comment by neoranger** [comment]
Issue solucionado en: https://github.com/ao-libre/ao-cliente/pull/761
