### ISSUE TITLE
Panel GM  - Seguimientos no estaria funcionando bien

### ISSUE THREAD

**Issue by RecoX** [ao-libre/ao-cliente#551]
Pareceria que el valor en Logueado Hace no esta bien

![image](https://user-images.githubusercontent.com/5874806/77238068-49c47d80-6c32-11ea-874c-0d33d8aeac7b.png)

**Comment by neoranger** [comment]
Y hay algunas funciones que no funcionan como revivir y otras más.

**Comment by CuicuiEB** [comment]
Acá estoy viendo y funciona bien, dibuja en formato hh:mm:ss
Lo de revivir también funciona bien
