### ISSUE TITLE
Posibilidad de acomodar items en el inventario

### ISSUE THREAD

**Issue by RecoX** [ao-libre/ao-cliente#56]
Implementar la posibilidad de modificar items en el inventario pudiendolos arrastrar en el slot indicado.

**Comment by Juanmz** [comment]
https://www.gs-zone.org/temas/drag-and-drop-arrastre-de-item.54798/ Lo único que hay que hacer de ese aporte es hacer una validación para que no arrastre el item fuera del inventario sino se bugea el gráfico.

**Comment by neoranger** [comment]
No se podrá manejar como se hace con los hechizos? En vez de arrastrar que se seleccione y con las flechitas de la derecha que se vaya moviendo de slot el item.
Flechita para arriba: Izquierda
Flechita para abajo: Derecha
Lo he visto en otros juegos y la verdad funciona bien y se entiende rápidamente su uso.

**Comment by RecoX** [comment]
Hecho por @FrankoH298
