### ISSUE TITLE
Chequear la limpieza el mundo

### ISSUE THREAD

**Issue by neoranger** [ao-libre/ao-cliente#565]
Usuario indica que la limpieza del mundo se hace muy consecutivamente. Se podrá chequear el intervalo de limpieza del mundo? También indica que se le limpiaron las cosas antes de dropear cuando murió.
Chequeó entre ir y venir al sacerdote para volver a buscar las cosas y no estaban.

**Comment by plusin** [comment]
El limpiar mundo no esta funcionando correctamente, el oro no se limpia, no se si es bug o es asi adrede. Saludos

**Comment by RecoX** [comment]
Esto ya podemos darlo por solucionado?

@cucsijuan  @CuicuiEB  pueden confirmar que ya esta todo bien?? y el oro se borra? deberia borrarse.

**Comment by cucsijuan** [comment]
ahi te confirmo, se que las bebidas y alguna comida no se borran, creo que figuraban como "carteles"

**Comment by cucsijuan** [comment]
confirmo que el oro no se borra, probe con otras botellitas que no se borran, el oro figura con el objType de los arboles, posible problema de dateo? lo mismo con las botellitas. 
![image](https://user-images.githubusercontent.com/25911526/88343894-cf5b5580-cd18-11ea-8fe6-d6b3118b1338.png)
