### ISSUE TITLE
Error de Automatizacion - 2005530518

### ISSUE THREAD

**Issue by RecoX** [ao-libre/ao-cliente#57]
Windows 7
No se sabe el por que
<img width="1200" alt="screen shot 2018-09-28 at 2 43 11 pm" src="https://user-images.githubusercontent.com/5874806/46185390-b1e01f00-c32d-11e8-96f9-189912b5ac62.png">

**Comment by Fhkek** [comment]
Las librerías.

**Comment by plusin** [comment]
> Las librerías.

Se un poco más especifico, este evento sucede en muchas ocasiones, nos sería útil poder resolverlo.

**Comment by RecoX** [comment]
Se pudo reproducir el error en Windows 7 64Bits con una instalacion limpia utilizando el setup NSIS

[!imagen](https://media.discordapp.net/attachments/489614122464313344/514650066531909632/Screen_Shot_2018-11-21_at_4.54.51_PM.png)

**Comment by juandpr** [comment]
Fixeado con el PR de Wolftein. #104
