### ISSUE TITLE
Posibilidad de acomodar lista de hechizos

### ISSUE THREAD

**Issue by RecoX** [ao-libre/ao-cliente#59]
Posibilidad de acomodar la lista de hechizos para ponerlos en el orden deseado.

**Comment by cucsijuan** [comment]
esto funciona correctamente, lo cierro.

**Comment by RecoX** [comment]
Re abro este ticket por que no funciona correctamente
Al querer cambiar de lugar un hechizo por otro funciona bien.

Al querer cambiar de lugar un hechizo en un slot vacio, se desconecta del servidor y va al main menu.
![Screen Shot 2019-04-25 at 4 06 23 PM](https://user-images.githubusercontent.com/5874806/56709251-5ddad300-6774-11e9-9e38-19585527504b.png)

**Comment by neoranger** [comment]
> Re abro este ticket por que no funciona correctamente
> Al querer cambiar de lugar un hechizo por otro funciona bien.
> 
> Al querer cambiar de lugar un hechizo en un slot vacio, se desconecta del servidor y va al main menu.
> ![Screen Shot 2019-04-25 at 4 06 23 PM](https://user-images.githubusercontent.com/5874806/56709251-5ddad300-6774-11e9-9e38-19585527504b.png)

Incluso a mi me pasó eso cuando le di doble click a un hechizo.

**Comment by jopiortiz** [comment]
Implementado y arreglado.
