### ISSUE TITLE
Monturas al desmontarse que aparezca el pj con todos los items equipados

### ISSUE THREAD

**Issue by RecoX** [ao-libre/ao-cliente#592]
Monturas al desmontarse que aparezca el pj con todos los items equipados
Cuando cambio de mapa y me bajo de la montura no todos los items aparecen equipados en el pj

**Comment by Jabyar** [comment]
Si estas equipado. Casco, ropa, escudo, arma. Subis a una montura, si bajas vos, dibuja bien el pj.

Si te baja un npc al golpearte te desaparecen los graficos del casco, escudo y arma. Solo ves la ropa.

Habria que probar que pasa si te baja otro usuario golpeandote, o con magia. 
![123](https://user-images.githubusercontent.com/6425148/79060871-4c7a2780-7c60-11ea-92e2-f75220539395.png)

**Comment by RecoX** [comment]
Creo que encontre el error en el codigo, es porque aparece esto despues de bajarte de la montura y no deberia:

Call ChangeUserChar(AtacanteIndex, .Char.body, .Char.Head, .Char.heading, NingunArma, NingunEscudo, NingunCasco)
