### ISSUE TITLE
Al pasar el mouse por encima de un pj se vuelve verde

### ISSUE THREAD

**Issue by RecoX** [ao-libre/ao-cliente#60]
Al pasar el mouse por encima de un personaje el mismo se vuelve verde.

<img width="1440" alt="screen shot 2018-09-29 at 4 26 20 pm" src="https://user-images.githubusercontent.com/5874806/46241019-9431b900-c404-11e8-8ce0-c5bd268179ca.png">

**Comment by cucsijuan** [comment]
Esto no seria un bug, es un overlay que le pusieron, para indicar que estas encima del char con el mouse.

**Comment by RecoX** [comment]
> Esto no seria un bug, es un overlay que le pusieron, para indicar que estas encima del char con el mouse.

Comprendo, que propones como solucion? Ya que el verde como que no indica eso, parece mas que esta envenado o que voy a envenarlo.

Opino que el hover podria transparentarlo mas al personaje (??) o resaltarlo de alguna forma un poco mas obvia.
