### ISSUE TITLE
Configuración en el launcher no funciona

### ISSUE THREAD

**Issue by neoranger** [ao-libre/ao-cliente#609]
Si aprieto en el botón de configuración abre el AO Setup (incluso lo actualiza, supuestamente) y puedo tocar todas las opciones como apagar la música de entrada o los efectos y demás, pero no funciona nada de eso. Todo lo que cambie no le da pelota cuando inicia el juego.

![image](https://user-images.githubusercontent.com/5490758/79350791-427d5080-7f0e-11ea-9f07-c330dcfdd586.png)

**Comment by RecoX** [comment]
Hay que eliminar ese boton o cambiarlo para que baje el Editor de Partículas para el sistema ORE ya que ese `ao-setup` no se utiliza mas y quedo obsoleto.

**Comment by RecoX** [comment]
Con la nueva version del launcher, esto queda resuelto.
