### ISSUE TITLE
Criminales con nombre violeta

### ISSUE THREAD

**Issue by RecoX** [ao-libre/ao-cliente#62]
Los criminales tienen nombre en violeta en vez de rojo

<img width="1440" alt="screen shot 2018-09-29 at 5 03 57 pm" src="https://user-images.githubusercontent.com/5874806/46241285-76ffe900-c40a-11e8-822b-7cb6e1b2c522.png">

**Comment by cucsijuan** [comment]
El violeta, significa "atacable" estimo que es para diferenciar a los del caos (Siendo uno también del caos) de un criminal normal, esto lo puedo volver a la normalidad modificando un dat si quieren.

**Comment by RecoX** [comment]
Me parece bien diferenciar entre Criminales del Caos y Criminales normales.

Lo que si creo es que hay que normalizar el color a travez de todo, es decir, que en ves de decir
`Ves a pLus <Criminal>` en rojo aparezca en violeta para que se comprenda mejor el por que .

**Comment by cucsijuan** [comment]
Retiro lo dicho, parece que esa era la idea, pero no esta implementado, simplemente pintaba de violeta a los criminales.

**Comment by CuidadosoBander** [comment]
No habría cambiado el estado a criminal pero sin actualizar el "atacable" (en violeta)? 
O sea... que el pj haya pasado de "atacable" a criminal pero quedó el color del estado anterior?
