### ISSUE TITLE
Revisar lista de amigos por que no funciona bien.

### ISSUE THREAD

**Issue by RecoX** [ao-libre/ao-cliente#667]
La gente agrega como amigo a alguien, aparece pero al rato no esta mas.

**Comment by CuicuiEB** [comment]
Cuando llamas al Unload de un formulario donde pusiste la data y luego lo volvés a llamar vas a ver el formulario por defecto..

Opción 1) No sé, se me ocurre ocupar un array con los nombres de los usuarios y cargarlo cada vez que se abra el frmAmigos, aprovechando que el servidor manda el lugar que ocupa de amigos se puede hacer algo así:

**mod_Declaraciones:**

Const MAX_AMIGOS as Byte = 50 ' en el server es el máximo, so..
Public amigos(1 to MAX_AMIGOS) as String


**frmAmigos:**

Public Sub ActualizarAmigos()

    Dim i As Long
    
    ListAmigos.Clear
    
    For i = 1 To MAX_AMIGOS
        If LenB(amigos(i)) > 0 Then
            Call ListAmigos.AddItem(amigos(i))
        Else
            Exit For
        End If
    Next i

End Sub


**Protocol:**

Private Sub HandleEnviarListDeAmigos()

    '***************************************************
    'Author: Abusivo#1215 (DISCORD)
    'LastModification: 06/07/2020 - Cuicui
    '***************************************************
    If incomingData.Length < 6 Then
        Err.Raise incomingData.NotEnoughDataErrCode
        Exit Sub
    End If

    On Error GoTo errhandler
    
    'This packet contains strings, make a copy of the data to prevent losses if it's not complete yet...
    Dim Buffer As New clsByteQueue
    Call Buffer.CopyBuffer(incomingData)

    'Remove packet ID
    Call Buffer.ReadByte

    Dim slot As Byte
    Dim nombreamigo As String
    
    slot = Buffer.ReadByte()
    
    nombreamigo = Buffer.ReadASCIIString()
    
    amigos(slot) = nombreamigo
    
    If frmAmigos.Visible Then
        Call frmAmigos.ActualizarLista
    End If
    
    'If we got here then packet is complete, copy data back to original queue
    Call incomingData.CopyBuffer(Buffer)

errhandler:

    Dim Error As Long
        Error = Err.number
        
    On Error GoTo 0

    'Destroy auxiliar buffer
    Set Buffer = Nothing

    If Error <> 0 Then Call Err.Raise(Error)
    
End Sub

**Comment by jopiortiz** [comment]
:+1:
