### ISSUE TITLE
Al tocar la parte superior de laventana en algunas partes cierra el cliente

### ISSUE THREAD

**Issue by veleta2** [ao-libre/ao-cliente#703]
**Que sistema operativo usas ? // What operating system and version?**

**Que hiciste para que ocurriera? // What did you do?**

**Que esperabas que pase? // What did you expect to happen?**

**Que fue lo que paso? // What actually happened?**

**Comment by RecoX** [comment]
Arreglado, pasaba en full screen por querer mover la ventana
