### ISSUE TITLE
Error 429 en tiempo de ejecución

### ISSUE THREAD

**Issue by plusin** [ao-libre/ao-cliente#71]
Error en el cliente, tengo todos los DLL registrados porque otros clientes me funcionan, ejecuté como Administrador el cliente por las dudas pero hay algo nuevo que rompió el cliente, no se si será falla de algun update que hayan hecho en el ao-server pero como la falla salta al abrir el Argentum.exe o al querer generarlo adjunto capturas de pantalla.

![error_compilar_ao13](https://user-images.githubusercontent.com/7727108/46367344-a5243980-c653-11e8-90c9-5b536328bda3.png)

**Comment by plusin** [comment]
Agrego contenido de frmCargando.log:

**Comment by RecoX** [comment]
Este no es problema de librerias, visual basic no esta cargando algunos archivos del proyecto.
Es por es que tira error de que no encuentra un tipo de clase.

Podras subir una screenshot mostrando todos los archivos que te carga el visual basic 6 ? Para corroborar que no es un error de carga de archivos.

**Comment by cucsijuan** [comment]
tambien puede ser un problema de ocx, o le falta alguno o lo tiene mal

**Comment by plusin** [comment]
Era falla de mi visual basic.
