### ISSUE TITLE
Click en HUD, el cliente se cierra

### ISSUE THREAD

**Issue by jalbano-nlb** [ao-libre/ao-cliente#723]
**¿Que sistema operativo usas ?** W10 Pro

**¿Que hiciste para que ocurriera?** Hago click en la zona superior al inventario. (Encima de los botones "Inventario/Hechizos")
![BugClient](https://user-images.githubusercontent.com/55196314/86606372-4a351a00-bf7e-11ea-89a2-7a79884ac736.JPG)

**¿Que esperabas que pase?** No debería de pasar nada.

**¿Que fue lo que paso?** El cliente se cierra instantáneamente.

**Comment by CuicuiEB** [comment]
Estando en pantalla completa?
