### ISSUE TITLE
Mostrar Ping en lista de servidores y ocultar servidores no online

### ISSUE THREAD

**Issue by RecoX** [ao-libre/ao-cliente#73]
Necesitamos mostrar una columa que diga el PING del servidor
Necesitamos ocultar los servidores que esten offline de la lista

**Comment by plusin** [comment]
Agrego cosa importante, si intentamos conectar a un servidor no-oficial tira una advertencia, a mi criterio si vamos a trabajar con un servidor libre y testeado esa advertencia está de mas, pero por otro lado puede haber gente mala que cague a los usuarios con virus/etc y esa advertencia cumple con su cometido...lo dejo a su criterio. Karina

**Comment by RecoX** [comment]
Con respecto a esa advertencia, es la que venia original en el codigo.

Lo que propongo que podemos hacer es, si se llega a intentar conectar a un servidor que no este en la lista nuestra, que muestre el cartel diciendo que no se esta conectando a un servidor "Aprobado"  o "Registrado" por la comunidad.

**Comment by plusin** [comment]
Excelente, en no se que versión original del ao también pasaba eso creo.

**Comment by RecoX** [comment]
Esto fue hecho en parte aqui:
https://github.com/ao-libre/ao-cliente/commit/6b0f3a8a25142306a77cecc3adc35aae393ae68c

Habria que mejorar la forma en que obtenemos la latencia y ocultar servidores offline.

**Comment by RecoX** [comment]
Hecho en parte, solo falta hacer que servidores que no estan en la lista puedan elegir el mapa seleccionado, ya que solo pueden elegir el mapa Alkon por el momento.
