### ISSUE TITLE
Runtime error al hacer click derecho

### ISSUE THREAD

**Issue by RecoX** [ao-libre/ao-cliente#74]
El error es cuando se realiza click derecho te tira run time.
Marcada la posicion del click.
![43375198_1075654562606174_4882914981286248448_n](https://user-images.githubusercontent.com/5874806/46587899-6bd64880-caef-11e8-8b4e-856bbce70597.png)

**Comment by RecoX** [comment]
I can move the window and click over there with right button without problem, probably this was fixed in without intention.

**Comment by Juanmz** [comment]
Ese runtime se produce en pantalla completa creo.

**Comment by augustoacerbo** [comment]
Ese error se produce, porque tiene el código para mover formularios y el problema esta en que si esta maximizado no te tendría que dejar mover. Solamente te tiene que dejar mover cuando esta en 800x600.

**Comment by RecoX** [comment]
Solucionado en este PR
https://github.com/ao-libre/ao-cliente/pull/146#issuecomment-459617479
