### ISSUE TITLE
Bug personajes trabajando

### ISSUE THREAD

**Issue by ErikAolibre** [ao-libre/ao-cliente#765]
Al poner /online muestra todos los personajes y cuando muestra la totalidad de personajes online entre parentecis deberia de mostrar los que estan trabajando y en realidad esta diciendo ej: 39 online (39 trabajando) cuando en realidad hay menos haciendo trabajos.

foto:

https://ibb.co/PFNwnB8

saludos

Erik

**Comment by waltersit0** [comment]
Esto no es bug, es intencional. solo los cazadores con 100 skills en supervivencia pueden ver quienes son trabajadores.

**Comment by jopiortiz** [comment]
Arreglado https://github.com/ao-libre/ao-server/commit/6b741716466cb2bd2c1544947e7afbaa4fddab3e

Se mostraba quienes eran trabajadores en vez de quienes estaban trabajando.
