### ISSUE TITLE
Falla la información del servidor en pantalla de conexión

### ISSUE THREAD

**Issue by plusin** [ao-libre/ao-cliente#767]
**Que sistema operativo usas ? // What operating system and version?**
Windows 10 Pro 64 bits

**Que hiciste para que ocurriera? // What did you do?**
Abri el cliente y modifique el server.ini

**Que esperabas que pase? // What did you expect to happen?**
Que la información este actualizada, es decir que coincida con lo que dice mi server.ini

**Que fue lo que paso? // What actually happened?**
La información de mi server Argentum Online Libre LaPlataVive no es la correcta, adjunto imagenes.

El ping es incorrecto, el nombre del server y la descripcion tambien, la cantidad de users online es correcta.

![capturaao1](https://user-images.githubusercontent.com/7727108/87611857-791a6100-c6df-11ea-862a-13e5b667d767.png)

**Comment by cemercuri** [comment]
![asd](https://user-images.githubusercontent.com/64177248/89252635-b1cb9d00-d5f0-11ea-8fe6-ab94ec56c6d4.png)
Actualmente carga bien la info.
**Issue para cerrar.**
