### ISSUE TITLE
Llueve pero no se ve la lluvia

### ISSUE THREAD

**Issue by nicofestu** [ao-libre/ao-cliente#770]
**Que sistema operativo usas ? // What operating system and version?**
Windows 10

**Que hiciste para que ocurriera? // What did you do?**
Loguie mientras llovia

**Que esperabas que pase? // What did you expect to happen?**
Que se vea la lluvia

**Que fue lo que paso? // What actually happened?**
La energia baja, se escucha la lluvia pero no se ve

**Comment by neoranger** [comment]
Para que se vea la lluvia tiene que estar el limite de FPS activado desde el launcher. Probalo y si es así cerrá el issue. Están tratando de que la lluvia se vea siempre pero de momento para verla hay que hacer eso. Saludos.
