### ISSUE TITLE
tirar objetos me kickea del servidor y crear ramitas tambien

### ISSUE THREAD

**Issue by pototoization** [ao-libre/ao-cliente#776]
**Que sistema operativo usas ? // What operating system and version?**
Windows 10
**Que hiciste para que ocurriera? // What did you do?**
tire 3 de madera, y cree ramitas
**Que esperabas que pase? // What did you expect to happen?**
que tire el objeto al piso y q haga las ramitas
**Que fue lo que paso? // What actually happened?**
me kickeo del servidor dos veces, una por tirar la madera y la otra por crear las ramitas

**Comment by RecoX** [comment]
Solucionado
