### ISSUE TITLE
No reproduce la musica del juego

### ISSUE THREAD

**Issue by Axel1457** [ao-libre/ao-cliente#777]
**Que sistema operativo usas ? // What operating system and version?**
Windows 8.1
**Que hiciste para que ocurriera? // What did you do?**
Simplemente entré al juego y no reproduce la musica en mayoria de mapas en los que estuve.
**Que esperabas que pase? // What did you expect to happen?**
Que al entrar al juego, haya musica xD
**Que fue lo que paso? // What actually happened?**
Al entrar a opciones, desactive y volví a activar la musica y nada, lo mismo pasa en el launcher, sigue sin cambios :'v

**Comment by RecoX** [comment]
No puedo reproducirlo.
