### ISSUE TITLE
No sube ninguna habilidad en estadisticas/no me deja lanzar hechizo

### ISSUE THREAD

**Issue by Axel1457** [ao-libre/ao-cliente#778]
**Que sistema operativo usas ? // What operating system and version?**
Windows 8.1
**Que hiciste para que ocurriera? // What did you do?**
Lanzar un hechizo y ver las habilidades.
**Que esperabas que pase? // What did you expect to happen?**
Atacar un npc con el dardo magico y ver las habilidades
**Que fue lo que paso? // What actually happened?**
No me dejó lanzar el hechizo, me figura que no tengo puntos de habilidad suficientes. 
Tengo dos PJ, un mago nivel 5 y un pala nivel 3, en ninguno puedo lanzar el hechizo dardo magico.
Reviso las estadisticas para ver cual es el problema y veo que no tengo ninguna en los dos pj.
Adjunto una imagen:
![imagen](https://user-images.githubusercontent.com/68520189/87887641-4e8d1880-c9fd-11ea-8a65-0d0efe7ac1f5.png)

**Comment by cemercuri** [comment]
No podés lanzar el hechizo porque, como te indica el juego, no tenés los skillspoints en la habilidad necesarios (6). Para poder usarlo tenés que asignar skills en Magia haciendo click abajo de tu nick en la interfaz (esa especie de +).

**Comment by RecoX** [comment]
> 
> 
> No podés lanzar el hechizo porque, como te indica el juego, no tenés los skillspoints en la habilidad necesarios (6). Para poder usarlo tenés que asignar skills en Magia haciendo click abajo de tu nick en la interfaz (esa especie de +).

Como dice el muchacho aca, no asignaste los skills iniciales, no hay error de programacion aca.
