### ISSUE TITLE
piedra q se puede atravesar a medias map:35 X:86 Y:80

### ISSUE THREAD

**Issue by pototoization** [ao-libre/ao-cliente#779]
**Que sistema operativo usas ? // What operating system and version?**
windows 10
**Que hiciste para que ocurriera? // What did you do?**
fui caminando buscando bichos
**Que esperabas que pase? // What did you expect to happen?**
que me choque contra la piedra
**Que fue lo que paso? // What actually happened?**
pude atravesar la piedra

**Comment by RecoX** [comment]
Solucionado o al menos no lo puedo reproducir en la version actual.
