### ISSUE TITLE
Atrapado

### ISSUE THREAD

**Issue by exemaniac** [ao-libre/ao-cliente#785]
**Que sistema operativo usas ? // What operating system and version?**
Windows 10
**Que hiciste para que ocurriera? // What did you do?**
Camine a un cambio de mapa
**Que esperabas que pase? // What did you expect to happen?**
que cruzara elmapa
**Que fue lo que paso? // What actually happened?**
quede atrapado dentro de tres tildes. supongo que salte una piedra o un lugar superpuesto.
![atrapado](https://user-images.githubusercontent.com/68678370/88255174-105a5800-cc8e-11ea-9080-ebd08acc26b5.jpg)

**Comment by RecoX** [comment]
@ReyarB si podes ver que pasa seria genial

**Comment by ReyarB** [comment]
![23-07-2020 19-09-09](https://user-images.githubusercontent.com/50249497/88343702-61169300-cd18-11ea-9ba0-e1d58f61ebbe.jpg)


no veo problemas aca.

**Comment by RecoX** [comment]
Barbaro, procedo a cerrar
