### ISSUE TITLE
Error Tunica Egregia de Mago Oscuro

### ISSUE THREAD

**Issue by plusin** [ao-libre/ao-cliente#805]
**Que sistema operativo usas ? // What operating system and version?**
Windows 10

**Que hiciste para que ocurriera? // What did you do?**
Compre Tunica en NPC de Caos

**Que esperabas que pase? // What did you expect to happen?**
Que la tunica sea la tunica y no una montura

**Que fue lo que paso? // What actually happened?**
La tunica es una montura

Obj 634

![errormontura](https://user-images.githubusercontent.com/7727108/88585871-063baf00-d02a-11ea-9d1f-aeb0b557bab0.png)

**Comment by RecoX** [comment]
Solucionado
