### ISSUE TITLE
donde se ve el sistema de movimiento 

### ISSUE THREAD

**Issue by agustinmono** [ao-libre/ao-cliente#810]
Hola,  como hago para ver el.sistema de movimiento, como es que ordena la prioridad en un objetivo? Es decis si dos personajes están a un tile de distancia y aprieta  la tecla al mismo tiempo para ir al tile vacío, como es que no se superponen? Donde y como elije la prioridad .

Gracias

**Comment by Wyr0X** [comment]
Hola. Los clientes pueden no coincidir en quién llega primero a un tile, pero en el servidor no hay ninguna dualidad: el paquete de moverse que recibió primero es el que procesa. El resto es corregir al usuario que "pisó" al otro, para que vuelva a la posición anterior. Podés ver el código acá: https://github.com/ao-libre/ao-server/blob/master/Codigo/Modulo_UsUaRiOs.bas#L979
