### ISSUE TITLE
PJ y GM no tiran oro con T 

### ISSUE THREAD

**Issue by plusin** [ao-libre/ao-cliente#862]
**Que sistema operativo usas ? // What operating system and version?** W10

**Que hiciste para que ocurriera? // What did you do?** INTENTE TIRAR ORO - TIRAR TODO ORO

**Que esperabas que pase? // What did you expect to happen?** TIRAR ORO - TIRAR TODO ORO

**Que fue lo que paso? // What actually happened?** NO FUNCIONA TIRAR ORO, NI TIRAR ORO SIENDO GM/PJ NORMAL

**Comment by RecoX** [comment]
Esto esta bien asi, sino un molesto puede floodear la consola de un gm. Para hablar con gms necesitar llamarlo con /gm

**Comment by RecoX** [comment]
Arreglo error.
