### ISSUE TITLE
Susurros

### ISSUE THREAD

**Issue by plusin** [ao-libre/ao-cliente#863]
**Que sistema operativo usas ? // What operating system and version?** W10

**Que hiciste para que ocurriera? // What did you do?** Intente mandar susurro a un GM usando \NICKGM

**Que esperabas que pase? // What did you expect to happen?** Que el susurro le llegue al GM

**Que fue lo que paso? // What actually happened?** Los PJ normales no pueden enviarle susurros al GM mas si el GM puede susurrarles, no debería ser parejo? abro hilo.

**Comment by RecoX** [comment]
Esto esta bien asi, sino un molesto puede floodear la consola de un gm. Para hablar con gms necesitar llamarlo con /gm
