### ISSUE TITLE
Lo de la via publica es un chiste. Ya arreglen eso.

### ISSUE THREAD

**Issue by josead** [ao-libre/ao-cliente#888]
**Que sistema operativo usas ? // What operating system and version?**

**Que hiciste para que ocurriera? // What did you do?**

**Que esperabas que pase? // What did you expect to happen?**

**Que fue lo que paso? // What actually happened?**

**Comment by RecoX** [comment]
Lo de la via publica no es un chiste, sino es un trigger anti-piquete. El mismo es para evitar que personajes se queden parados en puntos clave como entradas de ciudades imposibilitando al resto de jugadores a entrar.

Podes quedarte quieto en cualquier otro lugar menos en esos puntos.
