### ISSUE TITLE
Crear personaje no se ven cuerpos

### ISSUE THREAD

**Issue by RecoX** [ao-libre/ao-cliente#93]
Al crear personajes no se ven los cuerpos para seleccionar:

![screen shot 2018-11-10 at 11 08 53 am](https://user-images.githubusercontent.com/5874806/48330538-b67c4f00-e6b1-11e8-9906-8c8a0cee7010.png)

**Comment by juandpr** [comment]
Estas seguro que se deberia ver algo ahi? Yo creo que siempre fue solo elegir la cabeza

**Comment by FrankoH298** [comment]
Hecho
