### ISSUE TITLE
Arreglar caracteres rotos / emoticones

### ISSUE THREAD

**Issue by RecoX** [ao-libre/ao-cliente#96]
Hay caracteres/emoticones que no se ven por ejemplo al querer hacer XD

![imagen](https://media.discordapp.net/attachments/495449714993659926/495449837647691786/bugsubirlevel.jpg)

**Comment by juandpr** [comment]
No sabia que teniamos emoticones en el AO, por mi los deshabilito jaja pero bueno

**Comment by RecoX** [comment]
Yo tampoco sabia, pero  deben de serlos, ya que al hacer XD  o :P sale un caracter roto.
